import numpy as np
a = np.array([[1,2,3], [4,5,6]])
b = np.zeros((3,4))
c = np.ones( (2,3,4), dtype = np.int64 ) 
d = np.empty( (2,3) )
e = np.arange(10,100, 10)

print(a)
print("==============")
print(b)
print("==============")
print(c)
print("==============")
print(d)
print("==============")
print(e)
print("==============")